#
# Module manifest for module 'AzWorkspaceManager'
#
# Generated by: Rogier Dijkman
#
# Generated on: 08/01/2025
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = 'AzWorkspaceManager.psm1'

    # Version number of this module.
    ModuleVersion     = '0.8.0'

    # ID used to uniquely identify this module
    GUID              = '67faa800-39f5-40ae-9ee8-6caac6ae1261'

    # Author of this module
    Author            = 'Rogier Dijkman'

    # Company or vendor of this module
    CompanyName       = ''

    # Copyright statement for this module
    Copyright         = '(c) Rogier Dijkman. All rights reserved.'

    # Description of the functionality provided by this module
    Description       = 'Helper module to manage and configure Microsoft Sentinel workspace manager'

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules   = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @(
        'Get-AzWorkspaceManager',
        'Add-AzWorkspaceManager',
        'Remove-AzWorkspaceManager',
        'Get-AzWorkspaceManagerMember',
        'Add-AzWorkspaceManagerMember',
        'Remove-AzWorkspaceManagerMember',
        'Get-AzWorkspaceManagerGroup',
        'Add-AzWorkspaceManagerGroup',
        'Remove-AzWorkspaceManagerGroup',
        'Get-AzWorkspaceManagerAssignment',
        'Add-AzWorkspaceManagerAssignment',
        'Remove-AzWorkspaceManagerAssignment',
        'Get-AzWorkspaceManagerAssignmentJob',
        'Add-AzWorkspaceManagerAssignmentJob',
        'Remove-AzWorkspaceManagerAssignmentJob',
        'Get-AzWorkspaceManagerItem'
    )

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport   = '*'

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport   = '*'

    # List of all files packaged with this module
    FileList = @(
        'Private\Get-AccessToken.ps1',
        'Private\Invoke-AzWorkspaceManager.ps1',
        'Private\Format-Result.ps1',
        'Private\Write-Message.ps1',
        'Private\Get-LogAnalyticsWorkspace.ps1',
        'Public\Get-AzWorkspaceManager.ps1',
        'Public\Add-AzWorkspaceManager.ps1',
        'Public\Remove-AzWorkspaceManager.ps1',
        'Public\Get-AzWorkspaceManagerMember.ps1',
        'Public\Add-AzWorkspaceManagerMember.ps1',
        'Public\Remove-AzWorkspaceManagerMember.ps1',
        'Public\Get-AzWorkspaceManagerGroup.ps1',
        'Public\Add-AzWorkspaceManagerGroup.ps1',
        'Public\Remove-AzWorkspaceManagerGroup.ps1',
        'Public\Get-AzWorkspaceManagerAssignment.ps1',
        'Public\Add-AzWorkspaceManagerAssignment.ps1',
        'Public\Remove-AzWorkspaceManagerAssignment.ps1',
        'Public\Get-AzWorkspaceManagerAssignmentJob.ps1',
        'Public\Add-AzWorkspaceManagerAssignmentJob.ps1',
        'Public\Remove-AzWorkspaceManagerAssignmentJob.ps1',
        'Public\Get-AzWorkspaceManagerItem.ps1',
        'AzWorkspaceManager.psd1',
        'AzWorkspaceManager.psm1'
    )

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{

        # IsPrerelease of this module
        IsPrerelease = $false

        PSData       = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags       = @("Sentinel", "Microsoft", "Azure", "WorkspaceManager", "ARM")

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/securehats/AzWorkspaceManager'

        } # End of PSData hashtable

    } # End of PrivateData hashtable

}
