name: Sign PowerShell Scripts
on:
  workflow_dispatch:

env:
  ARTIFACT_NAME: PowerShell.Workflows.ScriptSigning

jobs:
  sign_scripts:
    name: Sign and publish PowerShell scripts as pipeline artifacts
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
        with:  
          fetch-depth: 0  
      - name: Import code signing certificate
        env:
          NUGET_KEY: ${{ secrets.PS_GALLERY_KEY }}
          BASE64_PFX:  ${{ secrets.SIGNING_CERTIFICATE }}
          PFX_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        shell: pwsh
        run: |
          $pfxCertFilePath = Join-Path -Path $PSScriptRoot -ChildPath "CodeSigningCertificate.pfx"
          Set-Content -Value $([System.Convert]::FromBase64String($env:BASE64_PFX)) -Path $pfxCertFilePath -AsByteStream
          $codeSigningCert = Import-PfxCertificate -FilePath $pfxCertFilePath -Password $($env:PFX_PASSWORD | ConvertTo-SecureString -AsPlainText -Force) -CertStoreLocation Cert:\CurrentUser\My    
          #Copy-Item .\src\ -Recurse -Destination .\AzWorkspaceManager\ -Force
          #Publish-Module -Path .\AzWorkspaceManager\ -NuGetApiKey $env:NUGET_KEY
